M48
; DRILL file {KiCad (6.0.7)} date Tue Oct 18 19:39:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-18T19:39:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.6744Y-2.7545
X2.6744Y-2.9455
T2
X2.5551Y-2.7427
X2.5551Y-2.9573
T0
M30
